### ISSUE TITLE
Broken download link on Linux platform

### ISSUE THREAD

**Issue by evilive3000** [gladiatortoise/node-chromedriver-downloader#1]
I'm trying to use your youtube uploader but ran into a problem while crhomedriver installing.
```js
os.platform(); // "linux"
```
```
chromedriver or CHROMEDRIVER_VER_IS_88 is missing at /tmp/node-chromedriver-downloader
Downloading from https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_linux.zip..
Extracting zip to /tmp/node-chromedriver-downloader/chromedriver_linux_88.0.4324.96.zip..
Error: end of central directory record signature not found
    at /home/evilive/Projects/nvr/node_modules/yauzl/index.js:187:14
    at /home/evilive/Projects/nvr/node_modules/yauzl/index.js:631:5
    at /home/evilive/Projects/nvr/node_modules/fd-slicer/index.js:32:7
    at FSReqCallback.wrapper [as oncomplete] (node:fs:553:5)
```
The error due to the broken zip, because of the broken download link. Correct link should include `linux64`.

![image](https://user-images.githubusercontent.com/5011293/106338870-95f23c80-629d-11eb-8b8b-9e0d5763c651.png)

**Comment by gladiatortoise** [comment]
Thanks I'll fix this in a sec

**Comment by gladiatortoise** [comment]
Hey! Can you please try now? ```npm install node-apiless-youtube-upload@1.1.7```

Thanks

**Comment by evilive3000** [comment]
Hi, it's ok now. :+1:
thanks

**Comment by gladiatortoise** [comment]
Good to hear!
